/*
 Navicat Premium Dump SQL

 Source Server         : learnjava
 Source Server Type    : PostgreSQL
 Source Server Version : 170004 (170004)
 Source Host           : localhost:5432
 Source Catalog        : forexdb
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170004 (170004)
 File Encoding         : 65001

 Date: 01/03/2025 17:44:00
*/


-- ----------------------------
-- Sequence structure for exchange_rates_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."exchange_rates_id_seq";
CREATE SEQUENCE "public"."exchange_rates_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for transactions_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."transactions_id_seq";
CREATE SEQUENCE "public"."transactions_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for users_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."users_id_seq";
CREATE SEQUENCE "public"."users_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for exchange_rates
-- ----------------------------
DROP TABLE IF EXISTS "public"."exchange_rates";
CREATE TABLE "public"."exchange_rates" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "from_currency" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "rate" numeric(38,6) NOT NULL,
  "to_currency" varchar(255) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of exchange_rates
-- ----------------------------
INSERT INTO "public"."exchange_rates" VALUES (2, 'IDR', 0.010000, 'JPY');
INSERT INTO "public"."exchange_rates" VALUES (3, 'USD', 15625.000000, 'IDR');
INSERT INTO "public"."exchange_rates" VALUES (4, 'USD', 148.500000, 'JPY');
INSERT INTO "public"."exchange_rates" VALUES (5, 'JPY', 105.260000, 'IDR');
INSERT INTO "public"."exchange_rates" VALUES (6, 'JPY', 0.010000, 'USD');
INSERT INTO "public"."exchange_rates" VALUES (1, 'IDR', 0.000064, 'USD');

-- ----------------------------
-- Table structure for transactions
-- ----------------------------
DROP TABLE IF EXISTS "public"."transactions";
CREATE TABLE "public"."transactions" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "amount" numeric(38,2) NOT NULL,
  "converted_amount" numeric(38,2),
  "from_currency" varchar(255) COLLATE "pg_catalog"."default",
  "new_idr_balance" numeric(38,2),
  "new_jpy_balance" numeric(38,2),
  "new_usd_balance" numeric(38,2),
  "rate" numeric(38,6),
  "timestamp" timestamp(6) NOT NULL,
  "to_currency" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "transaction_type" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "user_id" int8 NOT NULL
)
;

-- ----------------------------
-- Records of transactions
-- ----------------------------
INSERT INTO "public"."transactions" VALUES (1, 700000.00, NULL, NULL, 1200000.00, 10000.00, 100.00, NULL, '2025-03-01 07:44:19.181395', 'IDR', 'DEPOSIT', 4);
INSERT INTO "public"."transactions" VALUES (2, 200000.00, 0.00, 'IDR', 1000000.00, 10000.00, 100.00, 0.000000, '2025-03-01 07:45:11.165368', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (3, 100000.00, 0.00, 'IDR', 900000.00, 10000.00, 100.00, 0.000000, '2025-03-01 07:46:56.024113', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (4, 100000.00, 6.00, 'IDR', 800000.00, 10000.00, 106.00, 0.000000, '2025-03-01 08:15:25.409294', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (5, 100000.00, 0.00, 'IDR', 700000.00, 10000.00, 106.00, 0.000000, '2025-03-01 10:28:49.303931', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (6, 100000.00, 0.00, 'IDR', 600000.00, 10000.00, 106.00, 0.000000, '2025-03-01 10:29:53.665582', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (7, 100000.00, 0.00, 'IDR', 500000.00, 10000.00, 106.00, 0.000000, '2025-03-01 10:32:05.219919', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (8, 9000000.00, NULL, NULL, 9500000.00, 10000.00, 106.00, NULL, '2025-03-01 10:32:51.744208', 'IDR', 'DEPOSIT', 4);
INSERT INTO "public"."transactions" VALUES (9, 1000000.00, 0.00, 'IDR', 8500000.00, 10000.00, 106.00, 0.000000, '2025-03-01 10:32:59.169982', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (10, 1000000.00, 0.00, 'IDR', 7500000.00, 10000.00, 106.00, 0.000000, '2025-03-01 10:35:41.000139', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (11, 1000000.00, 0.00, 'IDR', 6500000.00, 10000.00, 106.00, 0.000000, '2025-03-01 10:37:05.446289', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (12, 1000000.00, 60.00, 'IDR', 5500000.00, 10000.00, 166.00, 0.000060, '2025-03-01 10:38:56.645157', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (13, 1000000.00, 60.00, 'IDR', 4500000.00, 10000.00, 226.00, 0.000060, '2025-03-01 10:39:51.079771', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (14, 1000000.00, 60.00, 'IDR', 3500000.00, 10000.00, 286.00, 0.000060, '2025-03-01 10:39:54.733578', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (15, 1000000.00, 60.00, 'IDR', 2500000.00, 10000.00, 346.00, 0.000060, '2025-03-01 10:39:55.5961', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (16, 1000000.00, 60.00, 'IDR', 1500000.00, 10000.00, 406.00, 0.000060, '2025-03-01 10:39:58.632343', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (17, 1000000.00, 60.00, 'IDR', 500000.00, 10000.00, 466.00, 0.000060, '2025-03-01 10:39:58.832535', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (18, 90000000.00, NULL, NULL, 90500000.00, 10000.00, 466.00, NULL, '2025-03-01 10:54:22.045783', 'IDR', 'DEPOSIT', 4);
INSERT INTO "public"."transactions" VALUES (19, 1000000.00, 10000.00, 'IDR', 89500000.00, 20000.00, 466.00, 0.010000, '2025-03-01 10:54:47.195552', 'JPY', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (20, 1000000.00, 10000.00, 'IDR', 88500000.00, 30000.00, 466.00, 0.010000, '2025-03-01 10:54:55.159244', 'JPY', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (21, 1000000.00, 60.00, 'IDR', 87500000.00, 30000.00, 526.00, 0.000060, '2025-03-01 10:55:21.174819', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (22, 1000000.00, 60.00, 'IDR', 86500000.00, 30000.00, 586.00, 0.000060, '2025-03-01 10:55:27.807072', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (23, 1000000.00, 64.00, 'IDR', 85500000.00, 30000.00, 650.00, 0.000064, '2025-03-01 10:58:01.510518', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (24, 1000000.00, 64.00, 'IDR', 84500000.00, 30000.00, 714.00, 0.000064, '2025-03-01 10:58:07.23581', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (25, 100000.00, 6.40, 'IDR', 84400000.00, 30000.00, 720.40, 0.000064, '2025-03-01 10:58:19.1244', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (26, 100000.00, 6.40, 'IDR', 84300000.00, 30000.00, 726.80, 0.000064, '2025-03-01 11:00:17.292475', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (27, 100000.00, 6.40, 'IDR', 84200000.00, 30000.00, 733.20, 0.000064, '2025-03-01 11:00:22.165427', 'USD', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (28, 10000.00, 100.00, 'IDR', 84190000.00, 30100.00, 733.20, 0.010000, '2025-03-01 13:05:43.125449', 'JPY', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (29, 30000.00, 300.00, 'IDR', 84160000.00, 30400.00, 733.20, 0.010000, '2025-03-01 13:27:54.089293', 'JPY', 'EXCHANGE', 4);
INSERT INTO "public"."transactions" VALUES (30, 1000000.00, NULL, 'IDR', 83160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:29:16.944075', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (31, 1000000.00, NULL, 'IDR', 82160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:29:18.377735', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (32, 1000000.00, NULL, 'IDR', 81160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:29:36.840882', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (33, 1000000.00, NULL, 'IDR', 80160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:29:40.174758', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (34, 10000000.00, NULL, 'IDR', 70160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:29:45.015236', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (35, 10000000.00, NULL, 'IDR', 60160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:29:47.593229', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (36, 10000000.00, NULL, 'IDR', 50160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:29:49.600428', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (37, 10000000.00, NULL, 'IDR', 40160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:29:51.589866', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (38, 20000000.00, NULL, 'IDR', 20160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:30:03.641309', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (39, 5000000.00, NULL, 'IDR', 15160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:30:20.492994', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (40, 5000000.00, NULL, 'IDR', 10160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:30:43.266826', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (41, 5000000.00, NULL, 'IDR', 5160000.00, 30400.00, 733.20, NULL, '2025-03-01 13:30:43.732842', 'IDR', 'WITHDRAW', 4);
INSERT INTO "public"."transactions" VALUES (42, 2000.00, NULL, 'IDR', 5158000.00, 30400.00, 733.20, NULL, '2025-03-01 13:30:55.767611', 'IDR', 'WITHDRAW', 4);

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "address" varchar(255) COLLATE "pg_catalog"."default",
  "email" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "gender" varchar(255) COLLATE "pg_catalog"."default",
  "idr_balance" numeric(38,2) NOT NULL,
  "jpy_balance" numeric(38,2) NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "usd_balance" numeric(38,2) NOT NULL
)
;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO "public"."users" VALUES (1, 'Jl. Mawar No. 10', 'john@example.com', 'Male', 500000.00, 10000.00, 'John Doe', 100.00);
INSERT INTO "public"."users" VALUES (2, 'Jl. Melati No. 20', 'jane@example.com', 'Female', 750000.00, 15000.00, 'Jane Smith', 150.00);
INSERT INTO "public"."users" VALUES (4, 'bdg', 'agit@b.com', 'Male', 5158000.00, 30400.00, 'agit', 733.20);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."exchange_rates_id_seq"
OWNED BY "public"."exchange_rates"."id";
SELECT setval('"public"."exchange_rates_id_seq"', 6, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."transactions_id_seq"
OWNED BY "public"."transactions"."id";
SELECT setval('"public"."transactions_id_seq"', 42, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."users_id_seq"
OWNED BY "public"."users"."id";
SELECT setval('"public"."users_id_seq"', 4, true);

-- ----------------------------
-- Auto increment value for exchange_rates
-- ----------------------------
SELECT setval('"public"."exchange_rates_id_seq"', 6, true);

-- ----------------------------
-- Uniques structure for table exchange_rates
-- ----------------------------
ALTER TABLE "public"."exchange_rates" ADD CONSTRAINT "uko9hj74mvieg1qwb85xkq4mtb8" UNIQUE ("from_currency", "to_currency");

-- ----------------------------
-- Primary Key structure for table exchange_rates
-- ----------------------------
ALTER TABLE "public"."exchange_rates" ADD CONSTRAINT "exchange_rates_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for transactions
-- ----------------------------
SELECT setval('"public"."transactions_id_seq"', 42, true);

-- ----------------------------
-- Primary Key structure for table transactions
-- ----------------------------
ALTER TABLE "public"."transactions" ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for users
-- ----------------------------
SELECT setval('"public"."users_id_seq"', 4, true);

-- ----------------------------
-- Uniques structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "uk6dotkott2kjsp8vw4d0m25fb7" UNIQUE ("email");

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table transactions
-- ----------------------------
ALTER TABLE "public"."transactions" ADD CONSTRAINT "fkqwv7rmvc8va8rep7piikrojds" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
