--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-03-02 23:03:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 24586)
-- Name: rate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rate (
    id integer NOT NULL,
    kurs double precision,
    mata_uang_asal character varying(255),
    mata_uang_tujuan character varying(255)
);


ALTER TABLE public.rate OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24585)
-- Name: rate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4854 (class 0 OID 24586)
-- Dependencies: 220
-- Data for Name: rate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rate (id, kurs, mata_uang_asal, mata_uang_tujuan) FROM stdin;
1	16580	USD	IDR
2	150.6	USD	JPY
3	0.009084	IDR	JPY
4	6.031e-05	IDR	USD
5	0.006639	JPY	USD
6	140.7	JPY	IDR
7	10290	AUD	IDR
\.


--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 219
-- Name: rate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rate_id_seq', 7, true);


--
-- TOC entry 4707 (class 2606 OID 24592)
-- Name: rate rate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rate
    ADD CONSTRAINT rate_pkey PRIMARY KEY (id);


-- Completed on 2025-03-02 23:03:55

--
-- PostgreSQL database dump complete
--

