/*
 Navicat Premium Dump SQL

 Source Server         : localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 160002 (160002)
 Source Host           : localhost:5432
 Source Catalog        : bankadidastesting
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160002 (160002)
 File Encoding         : 65001

 Date: 02/03/2025 22:20:22
*/


-- ----------------------------
-- Sequence structure for foreign_exchange_markets_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."foreign_exchange_markets_id_seq";
CREATE SEQUENCE "public"."foreign_exchange_markets_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for foreign_exchange_markets_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."foreign_exchange_markets_seq";
CREATE SEQUENCE "public"."foreign_exchange_markets_seq" 
INCREMENT 50
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for transactions_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."transactions_id_seq";
CREATE SEQUENCE "public"."transactions_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for transactions_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."transactions_seq";
CREATE SEQUENCE "public"."transactions_seq" 
INCREMENT 50
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for customer_accounts
-- ----------------------------
DROP TABLE IF EXISTS "public"."customer_accounts";
CREATE TABLE "public"."customer_accounts" (
  "id" int4 NOT NULL,
  "type" varchar(255) COLLATE "pg_catalog"."default",
  "account" varchar(255) COLLATE "pg_catalog"."default",
  "balance" varchar(255) COLLATE "pg_catalog"."default",
  "customer_id" int4
)
;

-- ----------------------------
-- Records of customer_accounts
-- ----------------------------
INSERT INTO "public"."customer_accounts" VALUES (7, 'RMD', '190127102', '200000.0', 1);
INSERT INTO "public"."customer_accounts" VALUES (8, 'IDR', '80', '50000.0', 5);
INSERT INTO "public"."customer_accounts" VALUES (9, 'USD', '90', '3.125', 5);
INSERT INTO "public"."customer_accounts" VALUES (1, 'IDR', '1223', '10000.0', 1);
INSERT INTO "public"."customer_accounts" VALUES (2, 'USD', '4567', '8.75', 1);

-- ----------------------------
-- Table structure for customers
-- ----------------------------
DROP TABLE IF EXISTS "public"."customers";
CREATE TABLE "public"."customers" (
  "id" int4 NOT NULL,
  "address" varchar(255) COLLATE "pg_catalog"."default",
  "gender" varchar(255) COLLATE "pg_catalog"."default",
  "name" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of customers
-- ----------------------------
INSERT INTO "public"."customers" VALUES (1, 'GKM', 'L', 'Bintag');
INSERT INTO "public"."customers" VALUES (2, 'string', 'string', 'string');
INSERT INTO "public"."customers" VALUES (5, 'malang', 'L', 'Daffa');

-- ----------------------------
-- Table structure for foreign_exchange_markets
-- ----------------------------
DROP TABLE IF EXISTS "public"."foreign_exchange_markets";
CREATE TABLE "public"."foreign_exchange_markets" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "currency_from" varchar(255) COLLATE "pg_catalog"."default",
  "currency_to" varchar(255) COLLATE "pg_catalog"."default",
  "exchange_price" float4,
  "updated_at" timestamp(6)
)
;

-- ----------------------------
-- Records of foreign_exchange_markets
-- ----------------------------
INSERT INTO "public"."foreign_exchange_markets" VALUES (1, 'IDR', 'USD', 16000, '2025-03-11 01:51:36');
INSERT INTO "public"."foreign_exchange_markets" VALUES (2, 'IDR', 'YEN', 4000, '2025-03-02 02:34:49.753');
INSERT INTO "public"."foreign_exchange_markets" VALUES (3, 'IDR', 'RYD', 4000, '2025-03-02 02:34:49.753');
INSERT INTO "public"."foreign_exchange_markets" VALUES (4, 'IDR', 'RMA', 4000, '2025-03-02 02:34:49.753');
INSERT INTO "public"."foreign_exchange_markets" VALUES (5, 'IDR', 'JKL', 8000, '2025-03-02 02:34:49.753');
INSERT INTO "public"."foreign_exchange_markets" VALUES (6, 'string', 'string', 0, '2025-03-02 02:46:07.139');

-- ----------------------------
-- Table structure for transactions
-- ----------------------------
DROP TABLE IF EXISTS "public"."transactions";
CREATE TABLE "public"."transactions" (
  "id" int4 NOT NULL,
  "amount" float4 NOT NULL,
  "converted_amount" float4 NOT NULL,
  "date_time" timestamp(6),
  "exchange_rate_at_transaction" float4 NOT NULL,
  "from_account" varchar(255) COLLATE "pg_catalog"."default",
  "from_account_after_balance" float4 NOT NULL,
  "from_currency" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "status" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "to_account" varchar(255) COLLATE "pg_catalog"."default",
  "to_account_after_balance" float4 NOT NULL,
  "to_currency" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "customer_id" int4 NOT NULL,
  "exchange_rate_id" int4 NOT NULL
)
;

-- ----------------------------
-- Records of transactions
-- ----------------------------
INSERT INTO "public"."transactions" VALUES (102, 32000, 2, '2025-03-02 03:05:44.729281', 16000, '1223', 18000, 'IDR', 'SUCCESS', '4567', 2, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (152, 10000, 0.625, '2025-03-02 03:15:25.97091', 16000, '1223', 8000, 'IDR', 'SUCCESS', '4567', 2.625, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (202, 1000, 0.0625, '2025-03-02 03:22:00.342012', 16000, '1223', 7000, 'IDR', 'SUCCESS', '4567', 2.6875, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (203, 1000, 0.0625, '2025-03-02 03:23:22.691773', 16000, '1223', 6000, 'IDR', 'SUCCESS', '4567', 2.75, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (204, 1000, 0.0625, '2025-03-02 03:24:29.413466', 16000, '1223', 5000, 'IDR', 'SUCCESS', '4567', 2.8125, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (252, 600, 0.0375, '2025-03-02 03:46:57.003952', 16000, '1223', 4400, 'IDR', 'SUCCESS', '4567', 2.85, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (253, 600, 0.0375, '2025-03-02 03:47:08.528378', 16000, '1223', 3800, 'IDR', 'SUCCESS', '4567', 2.8874998, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (302, 500, 0.03125, '2025-03-02 03:48:59.878558', 16000, '1223', 3300, 'IDR', 'SUCCESS', '4567', 2.9187498, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (352, 500, 0.03125, '2025-03-02 03:49:38.227583', 16000, '1223', 2800, 'IDR', 'SUCCESS', '4567', 2.9499998, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (353, 500, 0.03125, '2025-03-02 03:52:22.804599', 16000, '1223', 2300, 'IDR', 'SUCCESS', '4567', 2.9812498, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (2, 72300, 4.51875, '2025-03-02 21:50:20.093054', 16000, '1223', 30000, 'IDR', 'SUCCESS', '4567', 7.5, 'USD', 1, 1);
INSERT INTO "public"."transactions" VALUES (3, 20000, 1.25, '2025-03-02 22:13:36.158062', 16000, '1223', 10000, 'IDR', 'SUCCESS', '4567', 8.75, 'USD', 1, 1);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."foreign_exchange_markets_id_seq"
OWNED BY "public"."foreign_exchange_markets"."id";
SELECT setval('"public"."foreign_exchange_markets_id_seq"', 9, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."foreign_exchange_markets_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."transactions_id_seq"', 3, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."transactions_seq"', 401, true);

-- ----------------------------
-- Primary Key structure for table customer_accounts
-- ----------------------------
ALTER TABLE "public"."customer_accounts" ADD CONSTRAINT "customer_accounts_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table customers
-- ----------------------------
ALTER TABLE "public"."customers" ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for foreign_exchange_markets
-- ----------------------------
SELECT setval('"public"."foreign_exchange_markets_id_seq"', 9, true);

-- ----------------------------
-- Primary Key structure for table foreign_exchange_markets
-- ----------------------------
ALTER TABLE "public"."foreign_exchange_markets" ADD CONSTRAINT "foreign_exchange_markets_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table transactions
-- ----------------------------
ALTER TABLE "public"."transactions" ADD CONSTRAINT "transactions_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table customer_accounts
-- ----------------------------
ALTER TABLE "public"."customer_accounts" ADD CONSTRAINT "fk260iegb70hy2yhyh1xshkrbw7" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table transactions
-- ----------------------------
ALTER TABLE "public"."transactions" ADD CONSTRAINT "fkcne8oqipg6kq8wevmvd5i2diq" FOREIGN KEY ("exchange_rate_id") REFERENCES "public"."foreign_exchange_markets" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."transactions" ADD CONSTRAINT "fkpnnreq9lpejqyjfct60v7n7x1" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
